packages:
  - 'packages/*'
  - 'apps/*'
failIfNoMatch: true
injectWorkspacePackages: true
dedupeInjectedDeps: true
syncInjectedDepsAfterScripts:
  - build
onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 0
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
