// Generated by scripts/generate-module-sdk.mjs. Edit the protocol schemas, not this file.
import type { ModuleEventPayload } from './contract.ts';

export type AgentMode = "autopilot" | "interactive" | "plan";
export type AgentStatus = "failed" | "starting" | "stopping" | "up";
export type AskRequest = {
    allowFreeform?: boolean | undefined;
    choices?: string[] | undefined;
    question: string;
    requestId: string;
};
export type ContextTier = "default" | "long_context";
export type ElicitationRequest = {
    actions?: ("accept" | "cancel" | "decline")[] | undefined;
    message: string;
    requestId: string;
    source?: string | undefined;
};
export type ExitPlanModeAction = "autopilot_fleet" | "autopilot" | "exit_only" | "interactive";
export type ModelOption = {
    defaultReasoningEffort?: string | undefined;
    modelId: string;
    name: string;
    supportedReasoningEfforts?: string[] | undefined;
    supportsLongContext?: boolean | undefined;
};
export type ModuleHostIntentMap = {
    "roles/readiness": {
        body: {
            roles?: {
                moduleId: string;
                roleId: string;
            }[] | undefined;
            sessionId: string;
        };
        result: {
            appliedRoles?: {
                moduleId: string;
                moduleName: string;
                name: string;
                roleId: string;
            }[] | undefined;
            loaded: boolean;
            ready: boolean;
            reasons: string[];
            roles: {
                moduleId: string;
                moduleName: string;
                name: string;
                roleId: string;
            }[];
            rolesNeedReload?: boolean | undefined;
            sessionId: string;
        };
    };
    "session/get": {
        body: {
            sessionId: string;
        };
        result: {
            meta: {
                activeMcpOperations?: number | undefined;
                activeOperations?: number | undefined;
                activeSubagents?: number | undefined;
                activity?: {
                    abortable: boolean;
                    hasActiveWork: boolean;
                    mcp: {
                        pendingConnectionCount: number;
                    };
                    processing: boolean;
                    queue: {
                        inFlightSteeringCount: number;
                        pendingCount: number;
                        steeringCount: number;
                    };
                    sampledAt: number;
                    tasks: {
                        activeAgents: number;
                        activeShells: number;
                        unknown: number;
                    };
                } | null | undefined;
                appliedRoles?: {
                    moduleId: string;
                    moduleName: string;
                    name: string;
                    roleId: string;
                }[] | undefined;
                ask: {
                    allowFreeform?: boolean | undefined;
                    choices?: string[] | undefined;
                    question: string;
                    requestId: string;
                } | null;
                availableModels?: {
                    defaultReasoningEffort?: string | undefined;
                    modelId: string;
                    name: string;
                    supportedReasoningEfforts?: string[] | undefined;
                    supportsLongContext?: boolean | undefined;
                }[] | undefined;
                cancelling?: boolean | undefined;
                closing?: boolean | undefined;
                compacting?: boolean | undefined;
                controls?: {
                    compaction: "auto" | "manual" | "unknown" | null;
                    main: boolean;
                    sampledAt: number;
                    steering: {
                        id: string;
                        text: string;
                    }[];
                    tasks: {
                        id: string;
                        kind: "agent" | "shell";
                        status: "cancelled" | "completed" | "failed" | "idle" | "running";
                        title: string;
                    }[];
                    token: string;
                } | null | undefined;
                createdAt?: number | undefined;
                currentContextTier?: "default" | "long_context" | null | undefined;
                currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
                currentModelId?: string | undefined;
                currentReasoningEffort?: null | string | undefined;
                cwd: string;
                decisions?: ({
                    kind: "ask";
                    request: {
                        allowFreeform?: boolean | undefined;
                        choices?: string[] | undefined;
                        question: string;
                        requestId: string;
                    };
                } | {
                    kind: "elicitation";
                    request: {
                        actions?: ("accept" | "cancel" | "decline")[] | undefined;
                        message: string;
                        requestId: string;
                        source?: string | undefined;
                    };
                } | {
                    kind: "plan";
                    request: {
                        actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
                        planContent?: string | undefined;
                        recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
                        requestId: string;
                        summary: string;
                    };
                })[] | undefined;
                elicitation?: {
                    actions?: ("accept" | "cancel" | "decline")[] | undefined;
                    message: string;
                    requestId: string;
                    source?: string | undefined;
                } | null | undefined;
                error?: null | string | undefined;
                intent?: null | string | undefined;
                lastActivity: number;
                lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
                loaded: boolean;
                loading?: boolean | undefined;
                nativeName?: null | string | undefined;
                nativeNameUserSet?: boolean | undefined;
                nativeProcessing?: boolean | undefined;
                planRequest?: {
                    actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
                    planContent?: string | undefined;
                    recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
                    requestId: string;
                    summary: string;
                } | null | undefined;
                queue?: {
                    canSteer?: boolean | undefined;
                    id: string;
                    text: string;
                }[] | undefined;
                roles?: {
                    moduleId: string;
                    moduleName: string;
                    name: string;
                    roleId: string;
                }[] | undefined;
                rolesNeedReload?: boolean | undefined;
                scheduleCount?: number | undefined;
                sessionId: string;
                status: "error" | "idle" | "running" | "unloaded";
                title: string;
                todo?: {
                    done: number;
                    intent: null | string;
                    total: number;
                } | null | undefined;
            } | null;
        };
    };
    "session/new": {
        body: {
            cwd: string;
            roles?: {
                moduleId: string;
                roleId: string;
            }[] | undefined;
        };
        result: {
            sessionId: string;
        };
    };
    "session/rename": {
        body: {
            name: string;
            sessionId: string;
        };
        result: {
            ok: boolean;
            title?: string | undefined;
        };
    };
    "session/resources-prepare": {
        body: {
            mcpServers?: {
                name: string;
                tools?: string[] | undefined;
            }[] | undefined;
            sessionId: string;
            skills?: string[] | undefined;
        };
        result: {
            error?: string | undefined;
            mcpServers: {
                effect: "enabled" | "not_attempted" | "unchanged" | "unconfirmed";
                enabled: boolean | null;
                name: string;
                status: "connected" | "disabled" | "failed" | "needs-auth" | "not_configured" | "pending" | "stopped" | "unloaded" | null;
                tools: null | string[];
            }[];
            ok: boolean;
            sessionId: string;
            skills: {
                effect: "enabled" | "not_attempted" | "unchanged" | "unconfirmed";
                enabled: boolean | null;
                name: string;
            }[];
            tools: "initialized" | "not_attempted" | "unchanged" | "unconfirmed";
        };
    };
    prompt: {
        body: {
            attachments?: ({
                data: string;
                displayName?: string | undefined;
                mimeType: string;
                type: "blob";
            } | {
                displayName: string;
                filePath: string;
                selection?: {
                    end: {
                        character: number;
                        line: number;
                    };
                    start: {
                        character: number;
                        line: number;
                    };
                } | undefined;
                text?: string | undefined;
                type: "selection";
            } | {
                displayName?: string | undefined;
                path: string;
                type: "directory";
            } | {
                displayName?: string | undefined;
                path: string;
                type: "file";
            })[] | undefined;
            mode?: "enqueue" | "immediate" | undefined;
            sessionId: string;
            text: string;
        };
        result: {
            ok: boolean;
            queued?: boolean | undefined;
        };
    };
};
export type NativeAttachment = {
    data: string;
    displayName?: string | undefined;
    mimeType: string;
    type: "blob";
} | {
    displayName: string;
    filePath: string;
    selection?: {
        end: {
            character: number;
            line: number;
        };
        start: {
            character: number;
            line: number;
        };
    } | undefined;
    text?: string | undefined;
    type: "selection";
} | {
    displayName?: string | undefined;
    path: string;
    type: "directory";
} | {
    displayName?: string | undefined;
    path: string;
    type: "file";
};
export type NativeAttachmentDescriptor = {
    data?: string | undefined;
    displayName?: string | undefined;
    mimeType: string;
    omittedReason?: string | undefined;
    type: "blob";
} | {
    displayName: string;
    filePath: string;
    selection?: {
        end: {
            character: number;
            line: number;
        };
        start: {
            character: number;
            line: number;
        };
    } | undefined;
    text?: string | undefined;
    type: "selection";
} | {
    displayName?: string | undefined;
    path: string;
    type: "directory";
} | {
    displayName?: string | undefined;
    path: string;
    type: "file";
};
export type NativeChatEvent = {
    agentId?: string | undefined;
    data: Record<string, unknown>;
    ephemeral?: boolean | undefined;
    id: string;
    parentId?: null | string | undefined;
    parentToolCallId?: string | undefined;
    timestamp?: number | string | undefined;
    type: string;
};
export type PendingDecision = {
    kind: "ask";
    request: {
        allowFreeform?: boolean | undefined;
        choices?: string[] | undefined;
        question: string;
        requestId: string;
    };
} | {
    kind: "elicitation";
    request: {
        actions?: ("accept" | "cancel" | "decline")[] | undefined;
        message: string;
        requestId: string;
        source?: string | undefined;
    };
} | {
    kind: "plan";
    request: {
        actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
        planContent?: string | undefined;
        recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
        requestId: string;
        summary: string;
    };
};
export type PlanRequest = {
    actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
    planContent?: string | undefined;
    recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
    requestId: string;
    summary: string;
};
export type QueuedItem = {
    canSteer?: boolean | undefined;
    id: string;
    text: string;
};
export type ResourcePreparationEffect = "enabled" | "not_attempted" | "unchanged" | "unconfirmed";
export type ResourcePreparationResult = {
    error?: string | undefined;
    mcpServers: {
        effect: "enabled" | "not_attempted" | "unchanged" | "unconfirmed";
        enabled: boolean | null;
        name: string;
        status: "connected" | "disabled" | "failed" | "needs-auth" | "not_configured" | "pending" | "stopped" | "unloaded" | null;
        tools: null | string[];
    }[];
    ok: boolean;
    sessionId: string;
    skills: {
        effect: "enabled" | "not_attempted" | "unchanged" | "unconfirmed";
        enabled: boolean | null;
        name: string;
    }[];
    tools: "initialized" | "not_attempted" | "unchanged" | "unconfirmed";
};
export type RoleSelection = {
    moduleId: string;
    roleId: string;
};
export type ServerEvent = {
    activeMcpOperations?: number | undefined;
    activeOperations?: number | undefined;
    activeSubagents?: number | undefined;
    activity?: {
        abortable: boolean;
        hasActiveWork: boolean;
        mcp: {
            pendingConnectionCount: number;
        };
        processing: boolean;
        queue: {
            inFlightSteeringCount: number;
            pendingCount: number;
            steeringCount: number;
        };
        sampledAt: number;
        tasks: {
            activeAgents: number;
            activeShells: number;
            unknown: number;
        };
    } | null | undefined;
    appliedRoles?: {
        moduleId: string;
        moduleName: string;
        name: string;
        roleId: string;
    }[] | undefined;
    ask?: {
        allowFreeform?: boolean | undefined;
        choices?: string[] | undefined;
        question: string;
        requestId: string;
    } | null | undefined;
    availableModels?: {
        defaultReasoningEffort?: string | undefined;
        modelId: string;
        name: string;
        supportedReasoningEfforts?: string[] | undefined;
        supportsLongContext?: boolean | undefined;
    }[] | undefined;
    cancelling?: boolean | undefined;
    closing?: boolean | undefined;
    compacting?: boolean | undefined;
    controls?: {
        compaction: "auto" | "manual" | "unknown" | null;
        main: boolean;
        sampledAt: number;
        steering: {
            id: string;
            text: string;
        }[];
        tasks: {
            id: string;
            kind: "agent" | "shell";
            status: "cancelled" | "completed" | "failed" | "idle" | "running";
            title: string;
        }[];
        token: string;
    } | null | undefined;
    createdAt?: number | undefined;
    currentContextTier?: "default" | "long_context" | null | undefined;
    currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
    currentModelId?: string | undefined;
    currentReasoningEffort?: null | string | undefined;
    cwd?: string | undefined;
    decisions?: ({
        kind: "ask";
        request: {
            allowFreeform?: boolean | undefined;
            choices?: string[] | undefined;
            question: string;
            requestId: string;
        };
    } | {
        kind: "elicitation";
        request: {
            actions?: ("accept" | "cancel" | "decline")[] | undefined;
            message: string;
            requestId: string;
            source?: string | undefined;
        };
    } | {
        kind: "plan";
        request: {
            actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
            planContent?: string | undefined;
            recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
            requestId: string;
            summary: string;
        };
    })[] | undefined;
    elicitation?: {
        actions?: ("accept" | "cancel" | "decline")[] | undefined;
        message: string;
        requestId: string;
        source?: string | undefined;
    } | null | undefined;
    error?: null | string | undefined;
    intent?: null | string | undefined;
    lastActivity?: number | undefined;
    lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
    loaded?: boolean | undefined;
    loading?: boolean | undefined;
    nativeName?: null | string | undefined;
    nativeNameUserSet?: boolean | undefined;
    nativeProcessing?: boolean | undefined;
    planRequest?: {
        actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
        planContent?: string | undefined;
        recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
        requestId: string;
        summary: string;
    } | null | undefined;
    queue?: {
        canSteer?: boolean | undefined;
        id: string;
        text: string;
    }[] | undefined;
    roles?: {
        moduleId: string;
        moduleName: string;
        name: string;
        roleId: string;
    }[] | undefined;
    rolesNeedReload?: boolean | undefined;
    scheduleCount?: number | undefined;
    sessionId: string;
    status?: "error" | "idle" | "running" | "unloaded" | undefined;
    title?: string | undefined;
    todo?: {
        done: number;
        intent: null | string;
        total: number;
    } | null | undefined;
    type: "session/patch";
} | {
    agentStatus: "failed" | "starting" | "stopping" | "up";
    models: {
        defaultReasoningEffort?: string | undefined;
        modelId: string;
        name: string;
        supportedReasoningEfforts?: string[] | undefined;
        supportsLongContext?: boolean | undefined;
    }[];
    permissionPolicy: "allow-all";
    sessions: {
        activeMcpOperations?: number | undefined;
        activeOperations?: number | undefined;
        activeSubagents?: number | undefined;
        activity?: {
            abortable: boolean;
            hasActiveWork: boolean;
            mcp: {
                pendingConnectionCount: number;
            };
            processing: boolean;
            queue: {
                inFlightSteeringCount: number;
                pendingCount: number;
                steeringCount: number;
            };
            sampledAt: number;
            tasks: {
                activeAgents: number;
                activeShells: number;
                unknown: number;
            };
        } | null | undefined;
        appliedRoles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        ask: {
            allowFreeform?: boolean | undefined;
            choices?: string[] | undefined;
            question: string;
            requestId: string;
        } | null;
        availableModels?: {
            defaultReasoningEffort?: string | undefined;
            modelId: string;
            name: string;
            supportedReasoningEfforts?: string[] | undefined;
            supportsLongContext?: boolean | undefined;
        }[] | undefined;
        cancelling?: boolean | undefined;
        closing?: boolean | undefined;
        compacting?: boolean | undefined;
        controls?: {
            compaction: "auto" | "manual" | "unknown" | null;
            main: boolean;
            sampledAt: number;
            steering: {
                id: string;
                text: string;
            }[];
            tasks: {
                id: string;
                kind: "agent" | "shell";
                status: "cancelled" | "completed" | "failed" | "idle" | "running";
                title: string;
            }[];
            token: string;
        } | null | undefined;
        createdAt?: number | undefined;
        currentContextTier?: "default" | "long_context" | null | undefined;
        currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
        currentModelId?: string | undefined;
        currentReasoningEffort?: null | string | undefined;
        cwd: string;
        decisions?: ({
            kind: "ask";
            request: {
                allowFreeform?: boolean | undefined;
                choices?: string[] | undefined;
                question: string;
                requestId: string;
            };
        } | {
            kind: "elicitation";
            request: {
                actions?: ("accept" | "cancel" | "decline")[] | undefined;
                message: string;
                requestId: string;
                source?: string | undefined;
            };
        } | {
            kind: "plan";
            request: {
                actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
                planContent?: string | undefined;
                recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
                requestId: string;
                summary: string;
            };
        })[] | undefined;
        elicitation?: {
            actions?: ("accept" | "cancel" | "decline")[] | undefined;
            message: string;
            requestId: string;
            source?: string | undefined;
        } | null | undefined;
        error?: null | string | undefined;
        intent?: null | string | undefined;
        lastActivity: number;
        lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
        loaded: boolean;
        loading?: boolean | undefined;
        nativeName?: null | string | undefined;
        nativeNameUserSet?: boolean | undefined;
        nativeProcessing?: boolean | undefined;
        planRequest?: {
            actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
            planContent?: string | undefined;
            recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
            requestId: string;
            summary: string;
        } | null | undefined;
        queue?: {
            canSteer?: boolean | undefined;
            id: string;
            text: string;
        }[] | undefined;
        roles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        rolesNeedReload?: boolean | undefined;
        scheduleCount?: number | undefined;
        sessionId: string;
        status: "error" | "idle" | "running" | "unloaded";
        title: string;
        todo?: {
            done: number;
            intent: null | string;
            total: number;
        } | null | undefined;
    }[];
    type: "snapshot";
} | {
    moduleId: string;
    payload: {
        readonly [key: string]: ModuleEventPayload;
    } | boolean | null | number | readonly ModuleEventPayload[] | string;
    type: "module/event";
} | {
    moduleId: string;
    type: "module/invalidated";
} | {
    reason: "compaction" | "rewind";
    sessionId: string;
    type: "chat/invalidated";
} | {
    resources?: ("control" | "controls" | "identity" | "instructions" | "mcp" | "mode" | "model" | "models" | "plan" | "queue" | "schedule" | "skills" | "tasks" | "todo" | "usage")[] | undefined;
    sessionId: string;
    type: "session/invalidated";
} | {
    session: {
        activeMcpOperations?: number | undefined;
        activeOperations?: number | undefined;
        activeSubagents?: number | undefined;
        activity?: {
            abortable: boolean;
            hasActiveWork: boolean;
            mcp: {
                pendingConnectionCount: number;
            };
            processing: boolean;
            queue: {
                inFlightSteeringCount: number;
                pendingCount: number;
                steeringCount: number;
            };
            sampledAt: number;
            tasks: {
                activeAgents: number;
                activeShells: number;
                unknown: number;
            };
        } | null | undefined;
        appliedRoles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        ask: {
            allowFreeform?: boolean | undefined;
            choices?: string[] | undefined;
            question: string;
            requestId: string;
        } | null;
        availableModels?: {
            defaultReasoningEffort?: string | undefined;
            modelId: string;
            name: string;
            supportedReasoningEfforts?: string[] | undefined;
            supportsLongContext?: boolean | undefined;
        }[] | undefined;
        cancelling?: boolean | undefined;
        closing?: boolean | undefined;
        compacting?: boolean | undefined;
        controls?: {
            compaction: "auto" | "manual" | "unknown" | null;
            main: boolean;
            sampledAt: number;
            steering: {
                id: string;
                text: string;
            }[];
            tasks: {
                id: string;
                kind: "agent" | "shell";
                status: "cancelled" | "completed" | "failed" | "idle" | "running";
                title: string;
            }[];
            token: string;
        } | null | undefined;
        createdAt?: number | undefined;
        currentContextTier?: "default" | "long_context" | null | undefined;
        currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
        currentModelId?: string | undefined;
        currentReasoningEffort?: null | string | undefined;
        cwd: string;
        decisions?: ({
            kind: "ask";
            request: {
                allowFreeform?: boolean | undefined;
                choices?: string[] | undefined;
                question: string;
                requestId: string;
            };
        } | {
            kind: "elicitation";
            request: {
                actions?: ("accept" | "cancel" | "decline")[] | undefined;
                message: string;
                requestId: string;
                source?: string | undefined;
            };
        } | {
            kind: "plan";
            request: {
                actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
                planContent?: string | undefined;
                recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
                requestId: string;
                summary: string;
            };
        })[] | undefined;
        elicitation?: {
            actions?: ("accept" | "cancel" | "decline")[] | undefined;
            message: string;
            requestId: string;
            source?: string | undefined;
        } | null | undefined;
        error?: null | string | undefined;
        intent?: null | string | undefined;
        lastActivity: number;
        lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
        loaded: boolean;
        loading?: boolean | undefined;
        nativeName?: null | string | undefined;
        nativeNameUserSet?: boolean | undefined;
        nativeProcessing?: boolean | undefined;
        planRequest?: {
            actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
            planContent?: string | undefined;
            recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
            requestId: string;
            summary: string;
        } | null | undefined;
        queue?: {
            canSteer?: boolean | undefined;
            id: string;
            text: string;
        }[] | undefined;
        roles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        rolesNeedReload?: boolean | undefined;
        scheduleCount?: number | undefined;
        sessionId: string;
        status: "error" | "idle" | "running" | "unloaded";
        title: string;
        todo?: {
            done: number;
            intent: null | string;
            total: number;
        } | null | undefined;
    };
    type: "session/added";
} | {
    sessionId: string;
    type: "session/removed";
} | {
    status: "failed" | "starting" | "stopping" | "up";
    type: "agent/status";
};
export type SessionActivity = {
    abortable: boolean;
    hasActiveWork: boolean;
    mcp: {
        pendingConnectionCount: number;
    };
    processing: boolean;
    queue: {
        inFlightSteeringCount: number;
        pendingCount: number;
        steeringCount: number;
    };
    sampledAt: number;
    tasks: {
        activeAgents: number;
        activeShells: number;
        unknown: number;
    };
};
export type SessionControls = {
    compaction: "auto" | "manual" | "unknown" | null;
    main: boolean;
    sampledAt: number;
    steering: {
        id: string;
        text: string;
    }[];
    tasks: {
        id: string;
        kind: "agent" | "shell";
        status: "cancelled" | "completed" | "failed" | "idle" | "running";
        title: string;
    }[];
    token: string;
};
export type SessionMeta = {
    activeMcpOperations?: number | undefined;
    activeOperations?: number | undefined;
    activeSubagents?: number | undefined;
    activity?: {
        abortable: boolean;
        hasActiveWork: boolean;
        mcp: {
            pendingConnectionCount: number;
        };
        processing: boolean;
        queue: {
            inFlightSteeringCount: number;
            pendingCount: number;
            steeringCount: number;
        };
        sampledAt: number;
        tasks: {
            activeAgents: number;
            activeShells: number;
            unknown: number;
        };
    } | null | undefined;
    appliedRoles?: {
        moduleId: string;
        moduleName: string;
        name: string;
        roleId: string;
    }[] | undefined;
    ask: {
        allowFreeform?: boolean | undefined;
        choices?: string[] | undefined;
        question: string;
        requestId: string;
    } | null;
    availableModels?: {
        defaultReasoningEffort?: string | undefined;
        modelId: string;
        name: string;
        supportedReasoningEfforts?: string[] | undefined;
        supportsLongContext?: boolean | undefined;
    }[] | undefined;
    cancelling?: boolean | undefined;
    closing?: boolean | undefined;
    compacting?: boolean | undefined;
    controls?: {
        compaction: "auto" | "manual" | "unknown" | null;
        main: boolean;
        sampledAt: number;
        steering: {
            id: string;
            text: string;
        }[];
        tasks: {
            id: string;
            kind: "agent" | "shell";
            status: "cancelled" | "completed" | "failed" | "idle" | "running";
            title: string;
        }[];
        token: string;
    } | null | undefined;
    createdAt?: number | undefined;
    currentContextTier?: "default" | "long_context" | null | undefined;
    currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
    currentModelId?: string | undefined;
    currentReasoningEffort?: null | string | undefined;
    cwd: string;
    decisions?: ({
        kind: "ask";
        request: {
            allowFreeform?: boolean | undefined;
            choices?: string[] | undefined;
            question: string;
            requestId: string;
        };
    } | {
        kind: "elicitation";
        request: {
            actions?: ("accept" | "cancel" | "decline")[] | undefined;
            message: string;
            requestId: string;
            source?: string | undefined;
        };
    } | {
        kind: "plan";
        request: {
            actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
            planContent?: string | undefined;
            recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
            requestId: string;
            summary: string;
        };
    })[] | undefined;
    elicitation?: {
        actions?: ("accept" | "cancel" | "decline")[] | undefined;
        message: string;
        requestId: string;
        source?: string | undefined;
    } | null | undefined;
    error?: null | string | undefined;
    intent?: null | string | undefined;
    lastActivity: number;
    lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
    loaded: boolean;
    loading?: boolean | undefined;
    nativeName?: null | string | undefined;
    nativeNameUserSet?: boolean | undefined;
    nativeProcessing?: boolean | undefined;
    planRequest?: {
        actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
        planContent?: string | undefined;
        recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
        requestId: string;
        summary: string;
    } | null | undefined;
    queue?: {
        canSteer?: boolean | undefined;
        id: string;
        text: string;
    }[] | undefined;
    roles?: {
        moduleId: string;
        moduleName: string;
        name: string;
        roleId: string;
    }[] | undefined;
    rolesNeedReload?: boolean | undefined;
    scheduleCount?: number | undefined;
    sessionId: string;
    status: "error" | "idle" | "running" | "unloaded";
    title: string;
    todo?: {
        done: number;
        intent: null | string;
        total: number;
    } | null | undefined;
};
export type SessionResource = "control" | "controls" | "identity" | "instructions" | "mcp" | "mode" | "model" | "models" | "plan" | "queue" | "schedule" | "skills" | "tasks" | "todo" | "usage";
export type SessionResourcesPrepare = {
    mcpServers?: {
        name: string;
        tools?: string[] | undefined;
    }[] | undefined;
    sessionId: string;
    skills?: string[] | undefined;
};
export type SessionRole = {
    moduleId: string;
    moduleName: string;
    name: string;
    roleId: string;
};
export type SessionStatus = "error" | "idle" | "running" | "unloaded";
export type Snapshot = {
    agentStatus: "failed" | "starting" | "stopping" | "up";
    models: {
        defaultReasoningEffort?: string | undefined;
        modelId: string;
        name: string;
        supportedReasoningEfforts?: string[] | undefined;
        supportsLongContext?: boolean | undefined;
    }[];
    permissionPolicy: "allow-all";
    sessions: {
        activeMcpOperations?: number | undefined;
        activeOperations?: number | undefined;
        activeSubagents?: number | undefined;
        activity?: {
            abortable: boolean;
            hasActiveWork: boolean;
            mcp: {
                pendingConnectionCount: number;
            };
            processing: boolean;
            queue: {
                inFlightSteeringCount: number;
                pendingCount: number;
                steeringCount: number;
            };
            sampledAt: number;
            tasks: {
                activeAgents: number;
                activeShells: number;
                unknown: number;
            };
        } | null | undefined;
        appliedRoles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        ask: {
            allowFreeform?: boolean | undefined;
            choices?: string[] | undefined;
            question: string;
            requestId: string;
        } | null;
        availableModels?: {
            defaultReasoningEffort?: string | undefined;
            modelId: string;
            name: string;
            supportedReasoningEfforts?: string[] | undefined;
            supportsLongContext?: boolean | undefined;
        }[] | undefined;
        cancelling?: boolean | undefined;
        closing?: boolean | undefined;
        compacting?: boolean | undefined;
        controls?: {
            compaction: "auto" | "manual" | "unknown" | null;
            main: boolean;
            sampledAt: number;
            steering: {
                id: string;
                text: string;
            }[];
            tasks: {
                id: string;
                kind: "agent" | "shell";
                status: "cancelled" | "completed" | "failed" | "idle" | "running";
                title: string;
            }[];
            token: string;
        } | null | undefined;
        createdAt?: number | undefined;
        currentContextTier?: "default" | "long_context" | null | undefined;
        currentMode?: "autopilot" | "interactive" | "plan" | null | undefined;
        currentModelId?: string | undefined;
        currentReasoningEffort?: null | string | undefined;
        cwd: string;
        decisions?: ({
            kind: "ask";
            request: {
                allowFreeform?: boolean | undefined;
                choices?: string[] | undefined;
                question: string;
                requestId: string;
            };
        } | {
            kind: "elicitation";
            request: {
                actions?: ("accept" | "cancel" | "decline")[] | undefined;
                message: string;
                requestId: string;
                source?: string | undefined;
            };
        } | {
            kind: "plan";
            request: {
                actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
                planContent?: string | undefined;
                recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
                requestId: string;
                summary: string;
            };
        })[] | undefined;
        elicitation?: {
            actions?: ("accept" | "cancel" | "decline")[] | undefined;
            message: string;
            requestId: string;
            source?: string | undefined;
        } | null | undefined;
        error?: null | string | undefined;
        intent?: null | string | undefined;
        lastActivity: number;
        lastActivitySource?: "host-event-receipt" | "native-construction" | "native-persisted" | undefined;
        loaded: boolean;
        loading?: boolean | undefined;
        nativeName?: null | string | undefined;
        nativeNameUserSet?: boolean | undefined;
        nativeProcessing?: boolean | undefined;
        planRequest?: {
            actions?: ("autopilot_fleet" | "autopilot" | "exit_only" | "interactive")[] | undefined;
            planContent?: string | undefined;
            recommendedAction?: "autopilot_fleet" | "autopilot" | "exit_only" | "interactive" | undefined;
            requestId: string;
            summary: string;
        } | null | undefined;
        queue?: {
            canSteer?: boolean | undefined;
            id: string;
            text: string;
        }[] | undefined;
        roles?: {
            moduleId: string;
            moduleName: string;
            name: string;
            roleId: string;
        }[] | undefined;
        rolesNeedReload?: boolean | undefined;
        scheduleCount?: number | undefined;
        sessionId: string;
        status: "error" | "idle" | "running" | "unloaded";
        title: string;
        todo?: {
            done: number;
            intent: null | string;
            total: number;
        } | null | undefined;
    }[];
    type: "snapshot";
};
export type TodoProgress = {
    done: number;
    intent: null | string;
    total: number;
};
